# action.yml
name: Python test
runs:
  using: 'docker'
  image: 'Dockerfile_cicd'
on:
  push:
    branches: [ ci-cd ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install package
        run: |
          python setup.py develop --user
    - name: Test
        run: |
          python -m pytest


#    - name: Clean
#      if: ${{ always() }}
#      run: |
#          docker ps -a | grep Exit | cut -d ' ' -f 1 | xargs docker rm
#    - name: Install package
#      run: |
#        echo "TORCH_LIB=/usr/lib64/python3.6/site-packages/torch/lib:$TORCH_LIB" >> $GITHUB_ENV
#        docker run -i --gpus device=all --name rat_manylinux -v $(pwd):/rational_activations df31f4268b9b zsh
#        python setup.py install
#        python -m pytest