# action.yml
name: Python test
on:
  push:
    branches: [ ci-cd ]
jobs:
  gpu_checks:
    name: GPU Checks
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run GPU tests CUDA 10.1
      run: |
        cd .github/workflows
        CUDA_HOME="/usr/local/cuda-10.1/" PATH="/usr/local/cuda-10.1/bin":$PATH make docker-test-run-zsh
    - name: Run GPU tests CUDA 10.2
      run: |
        cd .github/workflows
        CUDA_HOME="/usr/local/cuda-10.2/" PATH="/usr/local/cuda-10.2/bin":$PATH make docker-test-run-zsh


    - name: Clean
      if: ${{ always() }}
      run: |
          docker ps -a | grep Exit | cut -d ' ' -f 1 | xargs docker rm
#    - name: Install package
#      run: |
#        echo "TORCH_LIB=/usr/lib64/python3.6/site-packages/torch/lib:$TORCH_LIB" >> $GITHUB_ENV
#        docker run -i --gpus device=all --name rat_manylinux -v $(pwd):/rational_activations df31f4268b9b zsh
#        python setup.py install
#        python -m pytest
# run: |
#        echo "CUDA_HOME=/usr/local/cuda-10.2/" >> $GITHUB_ENV
#        echo "PATH=/usr/local/cuda-10.2/bin:$PATH" >> $GITHUB_ENV
#        make docker-test-run-zsh
#steps:
  #    - uses: actions/checkout@v2
  #    - name: Build test image
  #      run: |
  #        make docker-test-image
  #    - name: Run GPU tests
  #      run: |
  #        make docker-test-run